# k-means clustering

In [3]:
import cv2 
import numpy as np

# reading images

In [4]:
img = cv2.imread("C:/Users/ADMIN/Pictures/hi.jpg")
img

array([[[254, 229, 101],
        [253, 231, 101],
        [250, 233, 100],
        ...,
        [239, 223,  87],
        [241, 225,  89],
        [244, 228,  92]],

       [[237, 221,  98],
        [237, 223,  97],
        [236, 227, 100],
        ...,
        [235, 218,  78],
        [237, 220,  80],
        [240, 223,  83]],

       [[238, 230, 106],
        [239, 232, 109],
        [240, 237, 115],
        ...,
        [234, 217,  72],
        [236, 219,  74],
        [239, 222,  77]],

       ...,

       [[ 42, 174,  81],
        [ 41, 174,  81],
        [ 36, 174,  80],
        ...,
        [ 67, 147,  70],
        [ 67, 147,  70],
        [ 67, 147,  70]],

       [[ 35, 167,  74],
        [ 34, 167,  74],
        [ 33, 169,  75],
        ...,
        [ 69, 151,  74],
        [ 69, 151,  74],
        [ 69, 151,  74]],

       [[ 32, 173,  76],
        [ 32, 173,  76],
        [ 32, 173,  76],
        ...,
        [ 71, 151,  74],
        [ 71, 151,  74],
        [ 71, 151,  74]]

# RGB convertion

In [6]:
imgrgb  = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

# Reshape

In [7]:
vec = imgrgb.reshape((-1,3))
vec

array([[101, 229, 254],
       [101, 231, 253],
       [100, 233, 250],
       ...,
       [ 74, 151,  71],
       [ 74, 151,  71],
       [ 74, 151,  71]], dtype=uint8)

# Float conversion

In [8]:
vec = np.float32(vec)
vec

array([[101., 229., 254.],
       [101., 231., 253.],
       [100., 233., 250.],
       ...,
       [ 74., 151.,  71.],
       [ 74., 151.,  71.],
       [ 74., 151.,  71.]], dtype=float32)

# iteration termination criteria

In [9]:
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER,100,1)

# cluster conditions

In [10]:
K = 3
attempts=100

# K-means clustering

In [14]:
compactness,label,center = cv2.kmeans(vec,K,None,criteria,attempts,cv2.KMEANS_PP_CENTERS)
center

array([[192.05212, 105.90306,  34.33505],
       [170.52852, 228.45636, 220.55782],
       [ 61.35942, 163.99203, 158.34862]], dtype=float32)

# Unit convertion

In [16]:
center = np.uint8(center)
center

array([[192, 105,  34],
       [170, 228, 220],
       [ 61, 163, 158]], dtype=uint8)

# Flattening and reshaping

In [17]:
res = center[label.flatten()]
res_img = res.reshape((imgrgb.shape))
res_img

array([[[170, 228, 220],
        [170, 228, 220],
        [170, 228, 220],
        ...,
        [170, 228, 220],
        [170, 228, 220],
        [170, 228, 220]],

       [[170, 228, 220],
        [170, 228, 220],
        [170, 228, 220],
        ...,
        [170, 228, 220],
        [170, 228, 220],
        [170, 228, 220]],

       [[170, 228, 220],
        [170, 228, 220],
        [170, 228, 220],
        ...,
        [ 61, 163, 158],
        [ 61, 163, 158],
        [170, 228, 220]],

       ...,

       [[ 61, 163, 158],
        [ 61, 163, 158],
        [ 61, 163, 158],
        ...,
        [ 61, 163, 158],
        [ 61, 163, 158],
        [ 61, 163, 158]],

       [[ 61, 163, 158],
        [ 61, 163, 158],
        [ 61, 163, 158],
        ...,
        [ 61, 163, 158],
        [ 61, 163, 158],
        [ 61, 163, 158]],

       [[ 61, 163, 158],
        [ 61, 163, 158],
        [ 61, 163, 158],
        ...,
        [ 61, 163, 158],
        [ 61, 163, 158],
        [ 61, 163, 158]]

# image

In [18]:
cv2.imshow('original',img)
cv2.imshow('segmented',res_img)

cv2.waitKey(0)
cv2.destroyAllWindows()